version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn trading_api:app --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /path/to/your/certificates:/etc/ssl/certs:ro this is a placeholder
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
