version: '3'

services:
  web:
    container_name: api_service
    build: .
    command: uvicorn trading_api:app --host 0.0.0.0 --port 8080
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    container_name: redis_service
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    container_name: reverse_proxy_service
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge