FROM python:3.9-slim

WORKDIR /app

# Copy the entire project directory into the container
COPY . /app

# Install packages in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install Redis client
RUN pip install redis

EXPOSE 8080

# Change the CMD to run from the correct directory
CMD ["uvicorn", "trading_api:app", "--host", "0.0.0.0", "--port", "8080"]