name: Bazaar Api

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH
      run: |
        echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > gce_key.pem
        chmod 600 gce_key.pem

    - name: Deploy to Compute Engine
      run: |
        ssh -i gce_key.pem -o StrictHostKeyChecking=no ${{ secrets.GCE_USER }}@${{ secrets.GCE_INSTANCE_IP }} '
          cd Bazaar-backend/docker &&
          git pull origin main &&
          docker-compose down &&
          docker-compose build --no-cache &&
          docker-compose up -d
        '

    - name: Print success message
      run: echo "Deployment success! Check the api vers to confirm."

